// <auto-generated />
using IncomePlannerDB.IncomePlannerDbService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncomePlannerDB.Migrations
{
    [DbContext(typeof(IncomePlannerDbContext))]
    [Migration("20230407111758_taxregimetablevalues")]
    partial class taxregimetablevalues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncomePlannerDB.IncomePlannerModels.TaxRegime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("RegimeType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxRegimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = false,
                            RegimeType = "Old Tax Regime"
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = true,
                            RegimeType = "New Tax Regime"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
